version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mistypay-postgres
    environment:
      POSTGRES_DB: mistypay_local
      POSTGRES_USER: mistypay
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mistypay-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
